# Generated by Django 5.0 on 2024-01-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('materialtype', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=500)),
                ('myfile', models.FileField(upload_to='')),
                ('posteddate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('newstext', models.CharField(max_length=1000)),
                ('postdate', models.CharField(max_length=30)),
            ],
        ),
    ]
